Repository TeamLEGWORK/LEGWORK, pull requests merged in 2021-11, with the labels that each got.

#40 Add in sky position, inclination, polarization
  changelog.md
  docs/demos/CompareSensitivityCurves.ipynb
  docs/demos/Horizon Distance Eccentric.ipynb
  docs/demos/Milky Way detection rate.ipynb
  legwork/evol.py
  legwork/psd.py
  legwork/snr.py
  legwork/source.py
  legwork/strain.py
  legwork/tests/test_sources.py
  legwork/tests/test_strains.py
  legwork/tests/test_utils.py
  legwork/utils.py
  legwork/verification_binaries.npy
  legwork/visualisation.py
  setup.cfg
Labels: enhancement

#49 Mostly updates to demos/tutorials, other fixes too
  changelog.md
  docs/demos.rst
  docs/demos/Horizon Distance Eccentric.ipynb
  docs/demos/HorizonDistance.ipynb
  docs/demos/Milky Way detection rate.ipynb
  docs/demos/VerificationBinaries.ipynb
  docs/notebooks/Derivations.ipynb
  docs/notebooks/Evolution.ipynb
  docs/notebooks/Quickstart.ipynb
  docs/notebooks/Source.ipynb
  docs/notebooks/Visualisation.ipynb
  docs/notebooks/refs.bib
  legwork/__init__.py
  legwork/_version.py
  legwork/psd.py
  legwork/snr.py
  legwork/source.py
  legwork/strain.py
  legwork/tests/test_evol.py
  legwork/tests/test_psd.py
  legwork/tests/test_sources.py
  legwork/tests/test_strains.py
  legwork/tests/test_utils.py
  legwork/utils.py
  legwork/visualisation.py
  requirements.txt
  setup.cfg
  setup.py
Labels: documentation, enhancement

#50 Allow users to specify custom confusion noise
  changelog.md
  docs/demos/TheRoleofEccentricity.ipynb
  docs/notebooks/Quickstart.ipynb
  docs/notebooks/Visualisation.ipynb
  legwork/evol.py
  legwork/psd.py
  legwork/snr.py
  legwork/source.py
  legwork/tests/test_psd.py
  legwork/tests/test_sources.py
  legwork/visualisation.py
Labels: enhancement

#56 Fix TianQin sensitivity curve
  changelog.md
  docs/demos/CompareSensitivityCurves.ipynb
  docs/index.rst
  docs/notebooks/Derivations.ipynb
  docs/notebooks/Visualisation.ipynb
  legwork/_version.py
  legwork/psd.py
Labels: bug
